[tox]
envlist = py312-django52, quality
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
allowlist_externals = make
dependency_groups = test
commands =
    make test

[testenv:quality]
runner = uv-venv-lock-runner
allowlist_externals = make
dependency_groups = quality
commands =
    make quality

[pycodestyle]
# W504 line break after binary operator
# E722 do not use bare 'except' (pylint will tell us about that)
ignore = E501, W504, E722
max_line_length = 120
exclude = settings
