# Generated by Django 2.2.24 on 2021-06-16 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lti_consumer', '0011_courseeditltifieldsenabledflag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseEditLTIFieldsEnabledFlag',
            new_name='CourseAllowPIISharingInLTIFlag',
        ),
    ]
