# Generated by Django 3.2.12 on 2022-03-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0013_auto_20210712_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonfiguration',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lticonfiguration',
            name='config_store',
            field=models.CharField(choices=[('CONFIG_ON_XBLOCK', 'Configuration Stored on XBlock fields'), ('CONFIG_ON_DB', 'Configuration Stored on this model'), ('CONFIG_EXTERNAL', 'Configuration Stored on external service')], default='CONFIG_ON_XBLOCK', max_length=255),
        ),
    ]
