# Generated by Django 2.2.14 on 2020-07-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0002_auto_20200717_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticonfiguration',
            name='config_store',
            field=models.CharField(choices=[('CONFIG_ON_XBLOCK', 'Configuration Stored on XBlock fields')], default='CONFIG_ON_XBLOCK', max_length=25),
        ),
    ]
