# Generated by Django 2.2.14 on 2020-07-17 17:44

from django.db import migrations, models
import django.db.models.deletion
import opaque_keys.edx.django.models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0003_auto_20200717_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiAgsLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(blank=True, max_length=50)),
                ('resource_link_id', opaque_keys.edx.django.models.UsageKeyField(blank=True, db_index=True, max_length=255, null=True)),
                ('score_maximum', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('start_date_time', models.DateTimeField(blank=True)),
                ('end_date_time', models.DateTimeField(blank=True)),
                ('lti_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti_consumer.LtiConfiguration')),
            ],
        ),
    ]
