# Generated by Django 2.2.14 on 2020-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0004_ltiagslineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ltiagslineitem',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ltiagslineitem',
            name='resource_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
