# Generated by Django 2.2.14 on 2020-07-17 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0006_auto_20200717_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ltiagslineitem',
            name='lti_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti_consumer.LtiConfiguration'),
        ),
    ]
