# Generated by Django 2.2.19 on 2021-03-01 14:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0010_backfill-empty-string-lti-config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticonfiguration',
            name='lti_config',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='LTI configuration data.'),
        ),
        migrations.AlterField(
            model_name='ltidlcontentitem',
            name='attributes',
            field=jsonfield.fields.JSONField(),
        ),
    ]
