# Generated by Django 2.2.20 on 2021-07-12 13:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0012_rename_courseeditltifieldsenabledflag_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lticonfiguration',
            name='lti_config',
            field=jsonfield.fields.JSONField(blank=True, default=dict, help_text='LTI configuration data.'),
        ),
        migrations.AlterField(
            model_name='ltidlcontentitem',
            name='attributes',
            field=jsonfield.fields.JSONField(),
        ),
    ]
