# Generated by Django 3.2.8 on 2021-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0013_auto_20210712_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonfiguration',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
    ]
