# Generated by Django 3.2.15 on 2022-11-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0015_add_additional_1p3_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonfiguration',
            name='lti_1p3_redirect_uris',
            field=models.JSONField(blank=True, default=list, help_text='Valid URLs the Tool may redirect you to. This may or may not be the same as the launch url.', verbose_name='LTI 1.3 Redirect URIs'),
        ),
    ]
