# Generated by Django 3.2.15 on 2022-11-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0016_lticonfiguration_lti_1p3_proctoring_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='lticonfiguration',
            name='lti_1p3_redirect_uris',
            field=models.JSONField(blank=True, default=list, help_text="Valid urls the Tool may request us to redirect the id token to. The redirect uris are often the same as the launch url/deep linking url so if this field is empty, it will use them as the default. If you need to use different redirect uri's, enter them here. If you use this field you must enter all valid redirect uri's the tool may request.", verbose_name='LTI 1.3 Redirect URIs'),
        ),
    ]
