# Generated by Django 5.2.12 on 2026-03-17 14:56

import uuid

import django.db.models.deletion
from django.db import migrations, models

import lti_consumer.models


class Migration(migrations.Migration):
    dependencies = [
        ('lti_consumer', '0019_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lti1p3Passport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                (
                    'lti_1p3_internal_private_key',
                    models.TextField(blank=True, help_text="Platform's generated Private key. Keep this value secret."),
                ),
                (
                    'lti_1p3_internal_private_key_id',
                    models.CharField(blank=True, help_text="Platform's generated Private key ID", max_length=255),
                ),
                (
                    'lti_1p3_internal_public_jwk',
                    models.TextField(blank=True, help_text="Platform's generated JWK keyset."),
                ),
                (
                    'lti_1p3_client_id',
                    models.CharField(
                        default=lti_consumer.models.generate_client_id,
                        help_text='Client ID used by LTI tool',
                        max_length=255,
                    ),
                ),
                (
                    'lti_1p3_tool_public_key',
                    models.TextField(
                        blank=True,
                        help_text="This is the LTI Tool's public key. This should be provided by the LTI Tool. One of either lti_1p3_tool_public_key or lti_1p3_tool_keyset_url must not be blank.",
                        verbose_name='LTI 1.3 Tool Public Key',
                    ),
                ),
                (
                    'lti_1p3_tool_keyset_url',
                    models.CharField(
                        blank=True,
                        help_text="This is the LTI Tool's JWK (JSON Web Key) Keyset (JWKS) URL. This should be provided by the LTI Tool. One of either lti_1p3_tool_public_key or lti_1p3_tool_keyset_url must not be blank.",
                        max_length=255,
                        verbose_name='LTI 1.3 Tool Keyset URL',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='lticonfiguration',
            name='lti_1p3_passport',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lti_consumer.lti1p3passport'
            ),
        ),
    ]
