# Generated by Django 5.2.11 on 2026-02-12 10:40

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lti_consumer', '0019_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiXBlockConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'location',
                    opaque_keys.edx.django.models.UsageKeyField(blank=True, db_index=True, max_length=255, null=True),
                ),
                (
                    'lti_configuration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='lti_consumer.lticonfiguration',
                    ),
                ),
            ],
        ),
    ]
