# Generated by Django 5.2.12 on 2026-03-09 10:27

import django.db.models.deletion
import opaque_keys.edx.django.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('lti_consumer', '0019_mariadb_uuid_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtiXBlockConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', opaque_keys.edx.django.models.UsageKeyField(db_index=True, max_length=255)),
                (
                    'lti_configuration',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to='lti_consumer.lticonfiguration',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='ltiagslineitem',
            name='lti_xblock_config',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti_consumer.ltixblockconfig'
            ),
        ),
        migrations.AddField(
            model_name='ltidlcontentitem',
            name='lti_xblock_config',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti_consumer.ltixblockconfig'
            ),
        ),
    ]
