# Generated by Django 5.2.12 on 2026-03-12 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('lti_consumer', '0021_migrate_config_id_to_blocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lticonfiguration',
            name='location',
        ),
    ]
