# Generated by Django 5.2.12 on 2026-03-18 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lti_consumer', '0021_create_lti_1p3_passport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lticonfiguration',
            name='lti_1p3_client_id',
        ),
        migrations.RemoveField(
            model_name='lticonfiguration',
            name='lti_1p3_internal_private_key',
        ),
        migrations.RemoveField(
            model_name='lticonfiguration',
            name='lti_1p3_internal_private_key_id',
        ),
        migrations.RemoveField(
            model_name='lticonfiguration',
            name='lti_1p3_internal_public_jwk',
        ),
        migrations.RemoveField(
            model_name='lticonfiguration',
            name='lti_1p3_tool_keyset_url',
        ),
        migrations.RemoveField(
            model_name='lticonfiguration',
            name='lti_1p3_tool_public_key',
        ),
    ]
