# Generated by Django 5.2.12 on 2026-03-31 07:34

import opaque_keys.edx.django.models
from django.db import migrations, models


def set_name_and_context_key(apps, _):
    """
    Copy name and context_key from Block to LTI1p3Passport.
    """
    from lti_consumer.plugin.compat import load_enough_xblock  # pylint: disable=import-outside-toplevel
    LtiConfiguration = apps.get_model("lti_consumer", "LtiConfiguration")
    for configuration in LtiConfiguration.objects.all():
        if not configuration.location:
            continue
        try:
            block = load_enough_xblock(configuration.location)
        except Exception as e:  # pylint: disable=broad-exception-caught
            print(f"Error loading xblock {configuration.location}: {e}")
        try:
            passport = configuration.lti_1p3_passport
            if passport and not passport.name:
                passport.name = f"Passport of {block.display_name}"
                passport.context_key = block.context_id
                passport.save()
        except Exception as e:  # pylint: disable=broad-exception-caught
            print(f"Error saving passport {passport}: {e}")


def backwards(*_):
    """Reverse the migration only for MariaDB databases."""


class Migration(migrations.Migration):
    dependencies = [
        ('lti_consumer', '0022_remove_lticonfiguration_lti_1p3_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lti1p3passport',
            name='context_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lti1p3passport',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lticonfiguration',
            name='location',
            field=opaque_keys.edx.django.models.UsageKeyField(
                blank=True, db_index=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.RunPython(
            code=set_name_and_context_key,
            reverse_code=backwards,
        ),
    ]
